name = "DiffusionLimitedAggregation"
uuid = "6d57ee59-ef59-4d23-b169-6778c84746f0"
version = "0.1.0"
authors = ["Matei Barbu <mateibarbu19@disroot.org>"]

[deps]
ArgParse = "c7e460c6-2fb9-53a9-8c5b-16f535851c63"
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
DelimitedFiles = "8bb1440f-4735-579b-a4ab-409b98df4dab"
InteractiveUtils = "b77e0a4c-d291-57a0-90e8-8db25a27a240"
JuliaC = "acedd4c2-ced6-4a15-accc-2607eb759ba2"
KernelAbstractions = "63c18a36-062a-441e-b654-da1e3ab1ce7c"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
OhMyThreads = "67456a42-1dca-4109-a031-0a68de7e3ad5"
OrderedCollections = "bac558e1-5e72-5ebc-8fee-abe8a469f55d"
PProf = "e4faabce-9ead-11e9-39d9-4379958e3056"
Profile = "9abbd945-dff8-562f-b5e8-e1ebf5ef1b79"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
YAML = "ddb6d928-2868-570f-bddf-ab3f9cf99eb6"

[compat]
ArgParse = "1.2.0"
BenchmarkTools = "1.6.3"
Dates = "1.11.0"
DelimitedFiles = "1.9.1"
InteractiveUtils = "1.11.0"
JuliaC = "0.2.2"
KernelAbstractions = "0.9.39"
LinearAlgebra = "1.12.0"
OhMyThreads = "0.8.3"
OrderedCollections = "1.8.1"
PProf = "3.2.0"
Profile = "1.11.0"
Random = "1.11.0"
YAML = "0.4.16"
julia = "1.12"

[apps.main]
